In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import sklearn.linear_model as lm
import src.random_matrix as rm
import statsmodels.api as sm

PATH = '/home/clarkson/data/us_eq/cache'

In [4]:
df = pd.read_pickle('{}/log_returns_cleaned.pkl'.format(PATH))

In [47]:
def estimate_residuals(factors, returns):
    """
    :param factors: factors matrix of size kxn
    :param returns: stock returns of size nxp
    """
    fr = pd.DataFrame(np.matmul(factors.T, returns.values), columns=returns.columns.values)
    # Fit OLS to get betas
    return np.sum()

def fit_lrs(y, X):
    return lm.LinearRegression(fit_intercept=False).fit(X, y)

def compute_factor_return(factor, stock_returns, stdevs):
    return factor.dot(stock_returns.values / stdevs)

In [54]:
# df.rolling(60).apply(estimate_residual)
def clean_NAs(data, perc=95):
    data.dropna(thresh=len(data.index)*(perc/100.0), axis=1, inplace=True)
    data.dropna(thresh=len(data.columns), axis=0, inplace=True)

data = df.iloc[:60]
clean_NAs(data)
train_data = data.iloc[:48]
test_data = data.iloc[48:60]

/home/clarkson/Projects/mini_1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/clarkson/Projects/mini_1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [58]:
def estimate_factors_pct_var(data):
    pca = PCA(n_components=0.75, svd_solver='full')
    pca.fit(train_data.values.T)
    return pca.transform(train_data.values.T)

f = estimate_factors_pct_var(train_data)

def estimate_betas(data, factors):
    fr = np.dot(data.values, f)
fr.shape
# fr['AA'].name
models = train_data.apply(lambda x: fit_lrs(train_data[x.name], fr))
test_fr = np.dot(test_data.values, f)
resid = test_data.apply(lambda x: x - models[x.name].predict(test_fr))
# fr.shape
# print(estimate_betas(test_data['AA']))
# print(test_data.iloc[-1])

IndentationError: expected an indented block (<ipython-input-58-10f21de4f850>, line 9)

In [49]:
models

ticker
AA      LinearRegression(copy_X=True, fit_intercept=Fa...
AABA    LinearRegression(copy_X=True, fit_intercept=Fa...
AAON    LinearRegression(copy_X=True, fit_intercept=Fa...
AAPL    LinearRegression(copy_X=True, fit_intercept=Fa...
ABC     LinearRegression(copy_X=True, fit_intercept=Fa...
                              ...                        
ZBRA    LinearRegression(copy_X=True, fit_intercept=Fa...
ZEUS    LinearRegression(copy_X=True, fit_intercept=Fa...
ZION    LinearRegression(copy_X=True, fit_intercept=Fa...
ZIXI    LinearRegression(copy_X=True, fit_intercept=Fa...
PKG     LinearRegression(copy_X=True, fit_intercept=Fa...
Length: 1024, dtype: object

In [44]:
x = np.ones(10)
print(x)
y = np.random.randint(10, size=10)
print(y)
x / y

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[7 9 8 3 8 7 9 4 4 0]


/homes/clarkson/PycharmProjects/mini_1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


array([0.14285714, 0.11111111, 0.125     , 0.33333333, 0.125     ,
       0.14285714, 0.11111111, 0.25      , 0.25      ,        inf])