In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import sklearn.linear_model as lm
import src.random_matrix as rm
import statsmodels.api as sm

PATH = '/data/hawfinch/clarkson/data/us_eq/cache'

In [20]:
df = pd.read_pickle('{}/log_returns_cleaned.pkl'.format(PATH))

In [53]:
def estimate_residuals(factors, returns):
    """
    :param factors: factors matrix of size kxn
    :param returns: stock returns of size nxp
    """
    fr = pd.DataFrame(np.matmul(factors.T, returns.values), columns=returns.columns.values)
    # Fit OLS to get betas
    return np.sum()

def estimate_betas(y, X):
    return lm.LinearRegression(intercept=False).fit(y, X).coef_

def compute_factor_return(factor, stock_returns, stdevs):
    return factor.dot(stock_returns.values / stdevs)

In [82]:
# df.rolling(60).apply(estimate_residual)
test_data = df.iloc[:60]
test_data.dropna(thresh=len(test_data.index)*.95, axis=1, inplace=True)
test_data.dropna(thresh=len(test_data.columns), axis=0, inplace=True)
test_data

/homes/clarkson/PycharmProjects/mini_1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/homes/clarkson/PycharmProjects/mini_1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


ticker            AA      AABA      AAON      AAPL       ABC      ABCB  \
date                                                                     
2000-02-01  0.037314 -0.014662 -0.068993 -0.034317  0.030563  0.012270   
2000-02-02  0.031142  0.032930  0.057158 -0.014443  0.009983  0.024098   
2000-02-03 -0.030032  0.093785  0.031253  0.044534 -0.006645 -0.024098   
2000-02-04 -0.025830 -0.018915  0.015268  0.044373 -0.016807 -0.012270   
2000-02-07 -0.032373  0.001413 -0.038615  0.054615 -0.006803  0.036368   
2000-02-08 -0.037108  0.052617  0.015625  0.007098 -0.024181 -0.024098   
2000-02-09 -0.018462 -0.029406  0.110001 -0.019781 -0.035591  0.000000   
2000-02-10  0.014185  0.007390  0.030772  0.007739 -0.010929 -0.012270   
2000-02-11  0.031940 -0.063078 -0.003373 -0.042751 -0.033523  0.024391   
2000-02-14  0.067648 -0.033191 -0.013606  0.062921 -0.007605 -0.024391   
2000-02-15  0.019216  0.025318 -0.074635  0.027151 -0.031010  0.000000   
2000-02-16 -0.001088 -0.050906  0.039788 -0.041829  0.003929  0.000000   
2000-02-17  0.041584  0.010008  0.000000  0.006550  0.049723  0.000000   
2000-02-18 -0.020043 -0.044243  0.000000 -0.032065 -0.065534  0.000000   
2000-02-22 -0.037453 -0.014923  0.021054  0.022772  0.003976  0.000000   
2000-02-23 -0.017295  0.077476 -0.003478  0.021191 -0.016000  0.006154   
2000-02-24 -0.023343  0.011125 -0.021128 -0.009046 -0.032790 -0.018576   
2000-02-25  0.009745 -0.017255 -0.003565 -0.042813 -0.068993  0.000000   
2000-02-28  0.013035 -0.019871 -0.007169  0.025714  0.035091  0.000000   
2000-02-29 -0.039041 -0.013992 -0.018149  0.012068  0.004301 -0.012579   
2000-03-01  0.016836 -0.007464 -0.033522  0.128270  0.021232  0.000000   
2000-03-02 -0.043536 -0.022733 -0.003795 -0.065914  0.004193  0.000000   
2000-03-03  0.016105  0.019573  0.007576  0.048009 -0.042742  0.000000   
2000-03-06 -0.016707  0.082353  0.026072 -0.018232 -0.031045  0.012579   
2000-03-07 -0.028687 -0.001093 -0.011091 -0.022631 -0.060343  0.000000   
2000-03-08  0.040054  0.032296  0.040078 -0.007147 -0.009615 -0.006270   
2000-03-09  0.002970  0.034702  0.014185  0.002047  0.004819  0.000000   
2000-03-10 -0.006546 -0.028717  0.020907  0.028228  0.000000  0.000000   
2000-03-13  0.015403 -0.012717 -0.003454 -0.035926 -0.009662  0.000000   
2000-03-14 -0.106602 -0.041000  0.000000 -0.059981 -0.070381  0.000000   
2000-03-15  0.046014 -0.062664 -0.028072  0.017354  0.131576  0.006270   
2000-03-16  0.068785  0.071146  0.024606  0.044685  0.175449  0.000000   
2000-03-17 -0.062558  0.005494 -0.021054  0.027885 -0.031131 -0.006270   
2000-03-20  0.014176  0.005191  0.021054 -0.016129  0.007874  0.000000   
2000-03-21  0.042534  0.108607 -0.013986  0.092627  0.003914  0.000000   
2000-03-22 -0.024341  0.027963 -0.016867  0.066303  0.000000  0.006270   
2000-03-23  0.040630 -0.031882  0.006247 -0.020141 -0.060381  0.000000   
2000-03-24  0.029004  0.015585  0.010620 -0.018751 -0.004158  0.000000   
2000-03-27  0.009484  0.034202 -0.007067  0.006289 -0.004175 -0.006270   
2000-03-28 -0.013416 -0.029061  0.007067 -0.003140  0.000000  0.006270   
2000-03-29  0.013971 -0.096497 -0.028574 -0.023178  0.004175  0.000000   
2000-03-30 -0.007240 -0.043650  0.028574 -0.077900 -0.033902  0.006231   
2000-03-31 -0.019758  0.011001 -0.010620  0.076979  0.033902  0.000000   
2000-04-03  0.018639 -0.067899 -0.003565 -0.018579 -0.025318 -0.006231   
2000-04-04 -0.014656  0.044282  0.014185 -0.046051  0.062132  0.024693   
2000-04-05 -0.018917 -0.010888 -0.028574  0.023770  0.031623 -0.024693   
2000-04-06  0.021186 -0.072396  0.042560 -0.040602  0.045635  0.012423   
2000-04-07 -0.043422 -0.018845  0.080043  0.051094 -0.003724  0.000000   
2000-04-10 -0.002370 -0.062720  0.000000 -0.052592 -0.073534  0.018349   
2000-04-11  0.040680 -0.061285  0.003200 -0.045521  0.092019  0.018018   
2000-04-12 -0.000570  0.019931 -0.009631 -0.089154  0.021740  0.005935   
2000-04-13 -0.009734 -0.000459  0.050325  0.040913  0.021277  0.000000   
2000

In [86]:
pca = PCA(n_components=0.75, svd_solver='full')
pca.fit(test_data.values.T)
t = pca.transform(test_data.values.T)

print(t.T.shape)
print(test_data.values.shape)
# print(test_data.columns.values)
# fr = pd.DataFrame(np.matmul(t.T, test_data.values), columns=test_data.columns.values)
print(test_data.iloc[-1].values)
print(t.shape)
fr = np.dot(t.T, test_data.iloc[-1].values)
fr
# fr['AA'].name
# betas = fr.apply(lambda x: estimate_betas(test_data[x.name], )

# fr.shape
# print(estimate_betas(test_data['AA']))
# print(test_data.iloc[-1])

(31, 1024)
(58, 1024)
[-0.00740745 -0.07809874  0.01499232 ...  0.01156082 -0.06103589
  0.02325686]
(1024, 31)


array([-2.42640842,  0.17560631,  0.35852756, -0.907378  , -1.06613941,
       -0.13848263, -0.26557261,  0.32602506,  0.98488241, -0.03422161,
       -0.16495535, -0.44581772,  0.2244865 ,  0.19105742, -0.28753527,
        0.09963997,  0.35940131, -0.35301512, -0.28199037, -0.34405933,
       -0.4082466 , -0.13902731,  0.15161987, -0.28409229,  0.33010472,
        0.06396258,  0.22338559, -0.12506894,  0.13704726, -0.12980892,
        0.11561571])

In [44]:
x = np.ones(10)
print(x)
y = np.random.randint(10, size=10)
print(y)
x / y

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[7 9 8 3 8 7 9 4 4 0]


/homes/clarkson/PycharmProjects/mini_1/venv/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


array([0.14285714, 0.11111111, 0.125     , 0.33333333, 0.125     ,
       0.14285714, 0.11111111, 0.25      , 0.25      ,        inf])